name: "B2500 Meter"
version: "main"
slug: b2500_meter
description: >-
  "Replicates a Smart Meter device for a B2500 energy storage system while allowing integration with various smart meters."
arch:
  - amd64
  - aarch64
  - armv7
url: "https://github.com/tomquist/b2500-meter"
panel_icon: "mdi:meter-electric"
init: false
startup: services
homeassistant_api: true
hassio_api: true
hassio_role: homeassistant
host_network: true
ports:
  12345/tcp: 12345
  12345/udp: 12345
options:
  power_input_alias: "sensor.current_power_in"
  power_output_alias: ""
  poll_interval: 1
  disable_absolute_values: false
  disable_sum_phases: false
schema:
  power_input_alias: str
  power_output_alias: str?
  poll_interval: int(1,)
  disable_absolute_values: bool
  disable_sum_phases: bool