name: Build Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
        description: "Container registry to use"
      platform:
        required: true
        type: string
        description: "Platform to build for (e.g. linux/amd64)"
      base:
        required: false
        type: string
        description: "Base image to use (e.g. distroless, alpine)"
        default: ""
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      image-suffix:
        required: true
        type: string
      digest-prefix:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - id: lower-repo
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}${{ inputs.image-suffix }}" >> $GITHUB_OUTPUT
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ steps.lower-repo.outputs.IMAGE_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platform }}
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          outputs: type=image,name=${{ inputs.registry }}/${{ steps.lower-repo.outputs.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ${{ inputs.build-args }}
            BASE=${{ inputs.base }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Export digest
        run: |
          mkdir -p /tmp/${{ inputs.digest-prefix }}digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/${{ inputs.digest-prefix }}digests/${digest#sha256:}"
      - name: Set platform name
        id: platform
        run: |
          SAFE_PLATFORM=$(echo "${{ inputs.platform }}" | sed 's|/|-|g')
          echo "name=$SAFE_PLATFORM" >> $GITHUB_OUTPUT
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.digest-prefix }}digests-${{ steps.platform.outputs.name }}
          path: /tmp/${{ inputs.digest-prefix }}digests/*
          if-no-files-found: error
          retention-days: 1