name: Merge Manifests

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
        description: "Container registry to use"
      image-suffix:
        required: true
        type: string
      digest-prefix:
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.digest-prefix }}digests-*
          path: /tmp/${{ inputs.digest-prefix }}digests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: lower-repo
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}${{ inputs.image-suffix }}" >> $GITHUB_OUTPUT
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ steps.lower-repo.outputs.IMAGE_NAME }}
      - name: Log in to Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: /tmp/${{ inputs.digest-prefix }}digests
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            # For non-PR events, create and push the manifest
            docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
              $(printf '${{ inputs.registry }}/${{ steps.lower-repo.outputs.IMAGE_NAME }}@sha256:%s ' *)
          else
            # For PRs, only create the manifest without pushing
            echo "Pull request detected - would create manifest with:"
            echo "Tags: $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")"
            echo "Digests: $(printf '${{ inputs.registry }}/${{ steps.lower-repo.outputs.IMAGE_NAME }}@sha256:%s ' *)"
          fi
      - name: Inspect image
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ inputs.registry }}/${{ steps.lower-repo.outputs.IMAGE_NAME }}:${{ steps.meta.outputs.version }}